name: Build for Linux

on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'Ref to build (branch, tag or SHA)'
        required: false
        default: 'master'

jobs:
  build:
    name: Build Tribute for Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.ref }}
      - name: Build it
        run: |
          swift build --configuration release
          SWIFTFORMAT_BIN_PATH=`swift build --configuration release --show-bin-path`
          mv $SWIFTFORMAT_BIN_PATH/tribute "${HOME}/tribute_linux"
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v2
        with:
          name: tribute_linux
          path: ~/tribute_linux
          retention-days: 5
